# /server/render.yaml
services:
  - type: web
    name: datanetplus-api
    env: node
    plan: free
    region: frankfurt
    rootDir: .
    buildCommand: "npm ci"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "https://your-username.github.io,https://your-username.github.io/datanetplus"
    healthCheckPath: /api/health
